<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="collaboration, confidence interval, effect size, open educational resource, open scholarship, open science">

<title>Guide to Effect Sizes and Confidence Intervals - 8&nbsp; Mean Differences</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Correlations.html" rel="next">
<link href="./Artifacts-and-Bias.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Guide to Effect Sizes and Confidence Intervals">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://matthewbjane.quarto.pub/effect-size-and-confidence-intervals-guide/social-preview.png">
<meta name="twitter:creator" content="@MatthewBJane">
<meta name="twitter:image-height" content="1417">
<meta name="twitter:image-width" content="2835">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Standardized-Mean-Differences.html"><strong>Standardized Effect Sizes</strong></a></li><li class="breadcrumb-item"><a href="./Standardized-Mean-Differences.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mean Differences</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="quarto-sidebar-header"><div class="sidebar-header-item">
<p><img src="margin-header.png" class="img-fluid"></p>
</div></div>
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Table of Contents</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/MatthewBJane/guide-to-effect-sizes-and-confidence-intervals" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Guide-to-Effect-Sizes-and-Confidence-Intervals.pdf">
              <i class="bi bi-bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Guide-to-Effect-Sizes-and-Confidence-Intervals.docx">
              <i class="bi bi-bi-file-word pe-1"></i>
            Download Docx
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Defining-Effect-Sizes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Defining Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reporting-Effect-Sizes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reporting Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Interpreting-Confidence-Intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interpreting Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reporting-Confidence-Intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Reporting Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Useful-R-Packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Using R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Artifacts-and-Bias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artifacts and Bias in Effect Sizes</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text"><strong>Standardized Effect Sizes</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Standardized-Mean-Differences.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mean Differences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Correlations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Categorical-Proportional-Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Categorical/Proportional Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Effect-Sizes-for-ANOVAs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Differences-in-Variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Variability Differences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Non-Parametric-Effect-Sizes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Non-Parametric Effect Sizes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text"><strong>Converting Between Effect Sizes</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Converting-to-Cohens-d.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Converting to Cohen’s d</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Converting-to-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Converting to Correlations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Converting-to-Odds-Ratio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Converting to Odds Ratios</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text"><strong>Conclusion</strong></span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Conclusion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#reporting-a-t-test-with-effect-size-and-ci" id="toc-reporting-a-t-test-with-effect-size-and-ci" class="nav-link active" data-scroll-target="#reporting-a-t-test-with-effect-size-and-ci"><span class="header-section-number">8.1</span> Reporting a t-test with effect size and CI</a></li>
  <li><a href="#sec-single-group" id="toc-sec-single-group" class="nav-link" data-scroll-target="#sec-single-group"><span class="header-section-number">8.2</span> Single Group Designs</a></li>
  <li><a href="#sec-two-ind-group" id="toc-sec-two-ind-group" class="nav-link" data-scroll-target="#sec-two-ind-group"><span class="header-section-number">8.3</span> Two Independent Groups Design</a>
  <ul class="collapse">
  <li><a href="#sec-two-ind-group-pooled" id="toc-sec-two-ind-group-pooled" class="nav-link" data-scroll-target="#sec-two-ind-group-pooled"><span class="header-section-number">8.3.1</span> Standardize by Pooled Standard Deviation (<span class="math inline">\(d_p\)</span>)</a></li>
  <li><a href="#sec-two-ind-group-glass" id="toc-sec-two-ind-group-glass" class="nav-link" data-scroll-target="#sec-two-ind-group-glass"><span class="header-section-number">8.3.2</span> Standardize by Control Group Standard Deviation (<span class="math inline">\(d_{\Delta}\)</span>)</a></li>
  </ul></li>
  <li><a href="#sec-repeated-measures" id="toc-sec-repeated-measures" class="nav-link" data-scroll-target="#sec-repeated-measures"><span class="header-section-number">8.4</span> Repeated Measures Designs</a>
  <ul class="collapse">
  <li><a href="#sec-repeated-measures-dz" id="toc-sec-repeated-measures-dz" class="nav-link" data-scroll-target="#sec-repeated-measures-dz"><span class="header-section-number">8.4.1</span> Difference Score <span class="math inline">\(d\)</span> (<span class="math inline">\(d_z\)</span>)</a></li>
  <li><a href="#sec-repeated-measures-drm" id="toc-sec-repeated-measures-drm" class="nav-link" data-scroll-target="#sec-repeated-measures-drm"><span class="header-section-number">8.4.2</span> Repeated Measures <span class="math inline">\(d\)</span> (<span class="math inline">\(d_{rm}\)</span>)</a></li>
  <li><a href="#sec-repeated-measures-dav" id="toc-sec-repeated-measures-dav" class="nav-link" data-scroll-target="#sec-repeated-measures-dav"><span class="header-section-number">8.4.3</span> Average Variance <span class="math inline">\(d\)</span> (<span class="math inline">\(d_{av}\)</span>)</a></li>
  <li><a href="#sec-becker" id="toc-sec-becker" class="nav-link" data-scroll-target="#sec-becker"><span class="header-section-number">8.4.4</span> Becker’s <span class="math inline">\(d\)</span> (<span class="math inline">\(d_b\)</span>)</a></li>
  <li><a href="#comparing-repeated-measures-d-values" id="toc-comparing-repeated-measures-d-values" class="nav-link" data-scroll-target="#comparing-repeated-measures-d-values"><span class="header-section-number">8.4.5</span> Comparing Repeated Measures <span class="math inline">\(d\)</span> values</a></li>
  </ul></li>
  <li><a href="#sec-ppc" id="toc-sec-ppc" class="nav-link" data-scroll-target="#sec-ppc"><span class="header-section-number">8.5</span> Pretest-Posttest-Control Group Designs</a>
  <ul class="collapse">
  <li><a href="#sec-ppc1" id="toc-sec-ppc1" class="nav-link" data-scroll-target="#sec-ppc1"><span class="header-section-number">8.5.1</span> PPC1 - separate pre-test standard deviations</a></li>
  <li><a href="#sec-ppc2" id="toc-sec-ppc2" class="nav-link" data-scroll-target="#sec-ppc2"><span class="header-section-number">8.5.2</span> PPC2 - pooled pre-test standard deviations</a></li>
  <li><a href="#sec-ppc3" id="toc-sec-ppc3" class="nav-link" data-scroll-target="#sec-ppc3"><span class="header-section-number">8.5.3</span> PPC3 - pooled pre- and post-test</a></li>
  </ul></li>
  <li><a href="#small-sample-bias-in-d-values" id="toc-small-sample-bias-in-d-values" class="nav-link" data-scroll-target="#small-sample-bias-in-d-values"><span class="header-section-number">8.6</span> Small Sample Bias in <span class="math inline">\(d\)</span> values</a></li>
  <li><a href="#sec-rr" id="toc-sec-rr" class="nav-link" data-scroll-target="#sec-rr"><span class="header-section-number">8.7</span> Ratios of Means</a>
  <ul class="collapse">
  <li><a href="#sec-rrind" id="toc-sec-rrind" class="nav-link" data-scroll-target="#sec-rrind"><span class="header-section-number">8.7.1</span> lnRR for Independent Groups (<span class="math inline">\(lnRR_\text{ind}\)</span>)</a></li>
  <li><a href="#sec-rrdep" id="toc-sec-rrdep" class="nav-link" data-scroll-target="#sec-rrdep"><span class="header-section-number">8.7.2</span> lnRR for dependent groups (<span class="math inline">\(lnRR_\text{dep}\)</span>)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Mean Differences</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>T-tests are the most commonly used statistical tests for examining differences between group means, or examining a group mean against a constant. Calculating effect sizes for t-tests is fairly straightforward. Nonetheless, there are cases where crucial figures for the calculation are missing (which happens quite often in older articles), and therefore we document methods that make use of partial information (e.g., only the M and the SD, or only the t-statistic and df) for the calculation. There are multiple types of effect sizes used to calculate standardized mean differences (i.e., Cohen’s <span class="math inline">\(d\)</span>), yet researchers very often do not identify which type of <span class="math inline">\(d\)</span> value they are reporting <span class="citation" data-cites="lakens2013">(see <a href="references.html#ref-lakens2013" role="doc-biblioref">Lakens 2013</a>)</span>. Here we document the equations and code necessary for calculating each type of <span class="math inline">\(d\)</span> value compiled across multiple sources <span class="citation" data-cites="becker1988 cohen1988 lakens2013 caldwell glass1981a">(<a href="references.html#ref-becker1988" role="doc-biblioref">Becker 1988</a>; <a href="references.html#ref-cohen1988" role="doc-biblioref">Cohen 1988</a>; <a href="references.html#ref-lakens2013" role="doc-biblioref">Lakens 2013</a>; <a href="references.html#ref-caldwell" role="doc-biblioref">Caldwell 2022</a>; <a href="references.html#ref-glass1981a" role="doc-biblioref">Glass, McGaw, and Smith 1981</a>)</span>. A <span class="math inline">\(d\)</span> value calculated from a sample will also contain sampling error, therefore we will also show the equations to calculate the standard error. The standard allows us to then calculate the confidence interval. For each formulation in the sections below, the confidence interval will be able to be calculated in the same way, that is,</p>
<p><span class="math display">\[
CI_d = d \pm 1.96\times SE
\]</span></p>
<p>Lastly, we will supply example R code so you can apply to your own data.</p>
<section id="here-is-a-table-for-every-effect-size-discussed-in-this-chapter" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="here-is-a-table-for-every-effect-size-discussed-in-this-chapter"><strong>Here is a table for every effect size discussed in this chapter:</strong></h4>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 43%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Description</th>
<th style="text-align: center;">Section</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Single Group Design</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"><a href="#sec-single-group"><span>Section&nbsp;8.2</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_s\)</span> - Single Group</td>
<td style="text-align: left;">Standardized mean difference for comparing a single group to some constant</td>
<td style="text-align: center;"><a href="#sec-single-group"><span>Section&nbsp;8.2</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Two Independent Groups Design</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"><a href="#sec-two-ind-group"><span>Section&nbsp;8.3</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_p\)</span> - Pooled Standard Deviation</td>
<td style="text-align: left;">Uses the average within-group standard deviation to standardize the mean difference. Can be calculated directly from a independent sample t-test. Assumes homogeneity of variance between groups.</td>
<td style="text-align: center;"><a href="#sec-two-ind-group-pooled"><span>Section&nbsp;8.3.1</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(d_\Delta\)</span> - Control Group Standard Deviation</td>
<td style="text-align: left;">Uses the standard deviation of the control group to standardize the mean difference (often referred to as Glass’s Delta). Does not assume homogeneity of variance between treatment/intervention and control group.</td>
<td style="text-align: center;"><a href="#sec-two-ind-group-glass"><span>Section&nbsp;8.3.2</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Repeated Measures (Paired Groups) Design</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"><a href="#sec-repeated-measures"><span>Section&nbsp;8.4</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(d_z\)</span> - Difference score standard deviation</td>
<td style="text-align: left;">Uses the standard deviation of difference scores (also known as change scores) to standardize the within person mean difference (i.e., pre/post change).</td>
<td style="text-align: center;"><a href="#sec-repeated-measures-dz"><span>Section&nbsp;8.4.1</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_{rm}\)</span> - Repeated measures</td>
<td style="text-align: left;">Uses the within-person standard deviation that utilizes a correction to <span class="math inline">\(d_z\)</span> to reduce the impact of the pre/post correlation on the effect size. Assumes homogeneity of variance between conditions.</td>
<td style="text-align: center;"><a href="#sec-repeated-measures-drm"><span>Section&nbsp;8.4.2</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(d_{av}\)</span> - Average variance</td>
<td style="text-align: left;">Uses the pooled variance between conditions (pre/post test). Does not use the correlation between conditions. Assumes homogeneity of variance between conditions.</td>
<td style="text-align: center;"><a href="#sec-repeated-measures-dav"><span>Section&nbsp;8.4.3</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_{b}\)</span> - Becker’s <em>d</em></td>
<td style="text-align: left;">Uses the pre-test standard deviation to standardize the pre/post mean difference. Does not assume homogeneity of variance between pre-test and post-test.</td>
<td style="text-align: center;"><a href="#sec-becker"><span>Section&nbsp;8.4.4</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Pre-Post-Control Design</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"><a href="#sec-ppc"><span>Section&nbsp;8.5</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_{PPC1}\)</span> - Separate pre-test standard deviations</td>
<td style="text-align: left;">Defined as the difference between the Becker’s <em>d</em> between the treatment and control group. Particularly, standardizing the mean pre/post change by the pre-test of the respective group.</td>
<td style="text-align: center;"><a href="#sec-ppc1"><span>Section&nbsp;8.5.1</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(d_{PPC2}\)</span> - Pooled pre-test standard deviation</td>
<td style="text-align: left;">Standardizes the difference in mean changes between treatment and control group. Assumes homogeneity of variance between the pre-test of the control and treatment condition.</td>
<td style="text-align: center;"><a href="#sec-ppc2"><span>Section&nbsp;8.5.2</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(d_{PPC3}\)</span> - Pooled pre-test and post-test standard deviation</td>
<td style="text-align: left;">Pools the standard deviation between pre-test and post-test in treatment and control condition. Assumes homogeneity of variance between pre/post-test scores <em>and</em> treatment and control conditions. Confidence intervals are not easy to compute.</td>
<td style="text-align: center;"><a href="#sec-ppc3"><span>Section&nbsp;8.5.3</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Mean Ratios</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: center;"><a href="#sec-rr"><span>Section&nbsp;8.7</span></a></td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(lnRR_\text{ind}\)</span> - Response ratio between independent groups</td>
<td style="text-align: left;">The ratio between the means between two groups. Does not use the standard deviation in the effect size formula.</td>
<td style="text-align: center;"><a href="#sec-rrind"><span>Section&nbsp;8.7.1</span></a></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(lnRR_\text{dep}\)</span> - Response ratio between dependent groups</td>
<td style="text-align: left;">The ratio between the means between two groups. Does not use the standard deviation in the effect size formula.</td>
<td style="text-align: center;"><a href="#sec-rrdep"><span>Section&nbsp;8.7.2</span></a></td>
</tr>
</tbody>
</table>
</section>
<section id="reporting-a-t-test-with-effect-size-and-ci" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="reporting-a-t-test-with-effect-size-and-ci"><span class="header-section-number">8.1</span> Reporting a t-test with effect size and CI</h2>
<p>Whatever effect size and CI you choose to report, you can report it alongside the t-test statistics (i.e., t-value and the p value):</p>
<blockquote class="blockquote">
<p>The treatment group had a significantly higher mean than the control group (<em>t</em> = 2.76, <em>p</em> = .009, <em>n</em> = 35, <em>d</em> = 0.47 [0.11, 0.81]).</p>
</blockquote>
</section>
<section id="sec-single-group" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-single-group"><span class="header-section-number">8.2</span> Single Group Designs</h2>
<p>For a single group design, we have one group and we want to compare the mean of that group to some constant, <span class="math inline">\(C\)</span> (i.e., a target value). The standardized mean difference for a single group can be calculated by <span class="citation" data-cites="cohen1988">(equation 2.3.3, <a href="references.html#ref-cohen1988" role="doc-biblioref">Cohen 1988</a>)</span>,</p>
<p><span class="math display">\[
d_s = \frac{M-C}{S_1}
\]</span></p>
<p>A positive <span class="math inline">\(d_s\)</span> value would indicate that the mean of group 1 is larger than the target value, <span class="math inline">\(C\)</span>. This formulation assumes that the sample is drawn from a normal distribution. The standardizer (i.e., the denominator) is the sample standard deviation. The corresponding standard error for <span class="math inline">\(d_s\)</span> is <span class="citation" data-cites="caldwell">(see documentation for <a href="references.html#ref-caldwell" role="doc-biblioref">Caldwell 2022</a>)</span>,</p>
<p><span class="math display">\[
SE_{d_s} = \sqrt{\frac{1}{n}+\frac{d_s^2}{2n}}.
\]</span></p>
<p>In R, we can use the <code>d.single.t</code> function from the <code>MOTE</code> package to calculate the single group standardized mean difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install packages if not already installed:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages('MOTE')</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for one group</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample Mean = 30.4, SD = 22.53, N = 96</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Target Value, C = 15</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MOTE)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">d.single.t</span>(</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">m =</span> <span class="fl">30.4</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">u =</span> <span class="dv">15</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fl">22.53</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">96</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.684 0.460 0.904</code></pre>
</div>
</div>
<p>As you can see, the output shows that the effect size is <span class="math inline">\(d_s\)</span> = 0.68, 95% CI [0.46, 0.90]. Note the <code>apa</code> function in <code>MOTE</code> takes a value and returns an APA formatted effect size value (i.e., leading zero and three decimal places).</p>
</section>
<section id="sec-two-ind-group" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="sec-two-ind-group"><span class="header-section-number">8.3</span> Two Independent Groups Design</h2>
<section id="sec-two-ind-group-pooled" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="sec-two-ind-group-pooled"><span class="header-section-number">8.3.1</span> Standardize by Pooled Standard Deviation (<span class="math inline">\(d_p\)</span>)</h3>
<p>For a two group design (i.e., between-groups design), we want to compare the means of two groups (group 1 and group 2). The standardized mean difference between two groups can be calculated by <span class="citation" data-cites="glass1981a">(equation 5.1, <a href="references.html#ref-glass1981a" role="doc-biblioref">Glass, McGaw, and Smith 1981</a>)</span>,</p>
<p><span class="math display">\[
d_p = \frac{M_1-M_2}{S_p}.
\]</span></p>
<p>A positive <span class="math inline">\(d_p\)</span> value would indicate that the mean of group 1 is larger than the mean of group 2. Dividing the mean difference by the pooled standard deviation, <span class="math inline">\(S_p\)</span>, is the classic formulation of Cohen’s <span class="math inline">\(d\)</span>. The pooled standard deviation, <span class="math inline">\(S_p\)</span>, can be calculated as the square root of the average variance (weighted by the degrees of freedom, <span class="math inline">\(df=n-1\)</span>) of group 1 and group 2 <span class="citation" data-cites="glass1981a">(pp.&nbsp;108, <a href="references.html#ref-glass1981a" role="doc-biblioref">Glass, McGaw, and Smith 1981</a>)</span>:</p>
<p><span class="math display">\[
S_p = \sqrt{\frac{(n_1-1)S_1^2 + (n_2-1)S_2^2}{n_1+n_2-2}}
\]</span></p>
<p>Note that the term <em>variance</em> refers to the square of the standard deviation (<span class="math inline">\(S^2\)</span>). Cohen’s <span class="math inline">\(d_p\)</span> has is related to the t-statistic from an independent samples t-test. In fact, we can calculate the <span class="math inline">\(d_p\)</span> value from the <span class="math inline">\(t\)</span>-statistic with the following formula <span class="citation" data-cites="glass1981a">(equation 5.3, <a href="references.html#ref-glass1981a" role="doc-biblioref">Glass, McGaw, and Smith 1981</a>)</span>:</p>
<p><span class="math display">\[
d = t\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}.
\]</span></p>
<p>The corresponding standard error of <span class="math inline">\(d_p\)</span> is,</p>
<p><span class="math display">\[
SE_{d_p} = \sqrt{\frac{n_1+n_2}{n_1 n_2}+\frac{d_p^2}{2(n_1+n_2)}}.
\]</span></p>
<p>In R, we can use the <code>d.ind.t</code> function from the <code>MOTE</code> package to calculate the two group standardized mean difference. Since we have already loaded in the <code>MOTE</code> package, we do not need to again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for two independent groups</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given means and SDs</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 1 Mean = 30.4, SD = 22.53, N = 96</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 2 Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">d.ind.t</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1 =</span> <span class="fl">30.4</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2 =</span> <span class="fl">21.4</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1 =</span> <span class="fl">22.53</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd2 =</span> <span class="fl">19.59</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">96</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="dv">96</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fl">0.05</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.426 0.140 0.712</code></pre>
</div>
</div>
<p>The output shows that the effect size is <span class="math inline">\(d_p\)</span> = 0.43, 95% CI [0.14, 0.71].</p>
</section>
<section id="sec-two-ind-group-glass" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="sec-two-ind-group-glass"><span class="header-section-number">8.3.2</span> Standardize by Control Group Standard Deviation (<span class="math inline">\(d_{\Delta}\)</span>)</h3>
<p>When two groups differ substantially in their standard deviations, we can instead standardize by the control group standard deviation (<span class="math inline">\(S_C\)</span>), such that,</p>
<p><span class="math display">\[
d_{\Delta} = \frac{M_T-M_C}{S_C}.
\]</span></p>
<p>Where the subscripts, <span class="math inline">\(T\)</span> and <span class="math inline">\(C\)</span>, denotes the treatment group and control group, respectively. This formulation is commonly referred to as Glass’ <span class="math inline">\(\Delta\)</span> <span class="citation" data-cites="glass1981">(<a href="references.html#ref-glass1981" role="doc-biblioref">Glass 1981</a>)</span>. The standard error for <span class="math inline">\(d_{\Delta}\)</span> can be defined as,</p>
<p><span class="math display">\[
SE_{d_{\Delta}} = \sqrt{\frac{n_T+n_C}{n_T n_C} + \frac{d_\Delta^2}{n_C+1} }
\]</span></p>
<p>Notice that when we only standardize by the standard deviation of the control group (rather than pooling), we he will have less degrees of freedom (<span class="math inline">\(df=n_C-1\)</span>) and therefore more sampling error than we do when we divide by the pooled standard deviation (<span class="math inline">\(df= n_T + n_C - 2\)</span>).In R, we can use the <code>delta.ind.t.diff</code> function from the <code>MOTE</code> package to calculate <span class="math inline">\(d_\Delta\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's dz for difference scores</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given difference score means and SDs</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Control group Mean = 30.4, SD = 22.53, N = 96</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Treatment group Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation between conditions: r = .40</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">delta.ind.t</span>(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1 =</span> <span class="fl">30.4</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2 =</span> <span class="fl">21.4</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1 =</span> <span class="fl">22.53</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd2 =</span> <span class="fl">19.59</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1 =</span> <span class="dv">96</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2 =</span> <span class="dv">96</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fl">0.05</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.399 0.140 0.712</code></pre>
</div>
</div>
</section>
</section>
<section id="sec-repeated-measures" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="sec-repeated-measures"><span class="header-section-number">8.4</span> Repeated Measures Designs</h2>
<p>In a repeated-measures design, the same subjects (or items, etc.) are measured on two or more separate occasions, or in multiple conditions within a single session, and we want to know the mean difference between those occasions or conditions <span class="citation" data-cites="baayen2008mixed barr2013random">(<a href="references.html#ref-baayen2008mixed" role="doc-biblioref">Baayen, Davidson, and Bates 2008</a>; <a href="references.html#ref-barr2013random" role="doc-biblioref">Barr et al. 2013</a>)</span>. An example of this would be in a pre/post comparison where subjects are tested before and after undergoing some treatment (see <a href="#fig-repeatedmeasures">Figure&nbsp;<span>8.1</span></a> for a visualization). A standardized mean difference in a repeated-measures design can take on a few different forms that we define below.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-repeatedmeasures" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Standardized-Mean-Differences_files/figure-html/fig-repeatedmeasures-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figure&nbsp;8.1: Figure displaying simulated data of a repeated measures design, the x-axis shows the condition (e.g., pre-test and post-test) and y-axis is the scores. Lines indicate within person pre/post change.</figcaption>
</figure>
</div>
</div>
</div>
<section id="sec-repeated-measures-dz" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="sec-repeated-measures-dz"><span class="header-section-number">8.4.1</span> Difference Score <span class="math inline">\(d\)</span> (<span class="math inline">\(d_z\)</span>)</h3>
<p>Instead of comparing the means of two sets of scores, a within subject design allows us to subtract the scores obtained in condition 1 from the scores in condition 2. These difference scores (<span class="math inline">\(X_{\text{diff}}=X_2-X_1\)</span>) can be used similarly to the single group design (if the target value was zero, i.e., <span class="math inline">\(C=0\)</span>) such that <span class="citation" data-cites="cohen1988">(equation 2.3.5, <a href="references.html#ref-cohen1988" role="doc-biblioref">Cohen 1988</a>)</span>,</p>
<p><span class="math display">\[
d_z = \frac{M_{\text{diff}}}{S_{\text{diff}}}
\]</span></p>
<p>Where the difference between this formulation and the single group design is the nature of the scores (difference scores rather than raw scores). The convenient thing about <span class="math inline">\(d_z\)</span> is that it has a straight-forward relationship with the <span class="math inline">\(t\)</span>-statistic, <span class="math inline">\(d_z=\frac{t}{\sqrt{n}}\)</span>. This makes it very useful for power analyses. If the standard deviation of difference scores are not accessible, then it can be calculated using the standard deviation of condition 1 (<span class="math inline">\(S_1\)</span>), the standard deviation of condition 2 (<span class="math inline">\(S_2\)</span>), and the correlation between conditions (<span class="math inline">\(r\)</span>) <span class="citation" data-cites="cohen1988">(equation 2.3.6, <a href="references.html#ref-cohen1988" role="doc-biblioref">Cohen 1988</a>)</span>:</p>
<p><span class="math display">\[
S_{\text{diff}}=\sqrt{S^2_1 + S^2_2 - 2 r S_1 S_2}
\]</span></p>
<p>It is important to note that when the correlation between groups is large, then the <span class="math inline">\(d_z\)</span> value will also be larger, whereas a small correlation will return a smaller <span class="math inline">\(d_z\)</span> value. The standard error of <span class="math inline">\(d_z\)</span> can be calculated similarly to the single group design such that,</p>
<p><span class="math display">\[
SE_{d_z} = \sqrt{\frac{1}{n}+\frac{d_z^2}{2n}}
\]</span></p>
<p>In R, we can use the <code>d.ind.t.diff</code> function from the <code>MOTE</code> package to calculate <span class="math inline">\(d_z\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's dz for difference scores</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given difference score means and SDs</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Difference Score Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MOTE)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">d.dep.t.diff</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">m =</span> <span class="fl">21.4</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fl">19.59</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">96</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fl">0.05</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 1.092 0.837 1.344</code></pre>
</div>
</div>
<p>The output shows that the effect size is <span class="math inline">\(d_z\)</span> = 1.09, 95% CI [0.84, 1.34].</p>
</section>
<section id="sec-repeated-measures-drm" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="sec-repeated-measures-drm"><span class="header-section-number">8.4.2</span> Repeated Measures <span class="math inline">\(d\)</span> (<span class="math inline">\(d_{rm}\)</span>)</h3>
<p>For a within-group design, we want to compare the means of scores obtained from condition 1 and condition 2. The repeated measures standardized mean difference between the two conditions can be calculated by <span class="citation" data-cites="lakens2013">(equation 9, <a href="references.html#ref-lakens2013" role="doc-biblioref">Lakens 2013</a>)</span>,</p>
<p><span class="math display">\[
d_{rm} = \frac{M_2-M_1}{S_w}.
\]</span></p>
<p>A positive <span class="math inline">\(d_{rm}\)</span> value would indicate that the mean of condition 2 is larger than the mean of condition 1. The standardizer here is the within-subject standard deviation, <span class="math inline">\(S_w\)</span>. The within-subject standard deviation can be defined as,</p>
<p><span class="math display">\[
S_{w}=\sqrt{\frac{S^2_1 + S^2_2 - 2 r S_1 S_2}{2(1-r)}}.
\]</span></p>
<p>We can also express <span class="math inline">\(S_w\)</span> in terms of the standard deviation of difference scores (<span class="math inline">\(S_{\text{diff}}\)</span>),</p>
<p><span class="math display">\[
S_w = \frac{S_{\text{diff}}}{ \sqrt{2(1-r)} }.
\]</span></p>
<p>Furthermore, we can even express <span class="math inline">\(d_{rm}\)</span> in terms of the difference score standardized mean difference (<span class="math inline">\(d_z\)</span>),</p>
<p><span class="math display">\[
d_{rm} = d_z \times \sqrt{2(1-r)}.
\]</span></p>
<p>Ultimately the <span class="math inline">\(d_{rm}\)</span> is more appropriate as an effect size estimate for use in meta-analysis whereas <span class="math inline">\(d_z\)</span> is more appropriate for power analysis <span class="citation" data-cites="lakens2013">(<a href="references.html#ref-lakens2013" role="doc-biblioref">Lakens 2013</a>)</span>. The standard error for <span class="math inline">\(d_{rm}\)</span> can be computed as,</p>
<p><span class="math display">\[
SE_{d_{rm}} = \sqrt{\left(\frac{1}{n} + \frac{d^2_{rm}}{2n}\right) \times 2(1-r)}
\]</span></p>
<p>In R, we can use the <code>d.ind.t.rm</code> function from the <code>MOTE</code> package to calculate the repeated measures standardized mean difference (<span class="math inline">\(d_{rm}\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for repeated measures</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given means and SDs and correlation</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 1 Mean = 30.4, SD = 22.53, N = 96</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 2 Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># correlation between conditions: r = .40</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">d.dep.t.rm</span>(</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1 =</span> <span class="fl">30.4</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2 =</span> <span class="fl">21.4</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1 =</span> <span class="fl">22.53</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd2 =</span> <span class="fl">19.59</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">r =</span> .<span class="dv">40</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">96</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fl">0.05</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.425 0.215 0.633</code></pre>
</div>
</div>
<p>The output shows that the effect size is <span class="math inline">\(d_{rm}\)</span> = 0.42, 95% CI [0.21, 0.63].</p>
</section>
<section id="sec-repeated-measures-dav" class="level3" data-number="8.4.3">
<h3 data-number="8.4.3" class="anchored" data-anchor-id="sec-repeated-measures-dav"><span class="header-section-number">8.4.3</span> Average Variance <span class="math inline">\(d\)</span> (<span class="math inline">\(d_{av}\)</span>)</h3>
<p>The problem with <span class="math inline">\(d_{z}\)</span> and <span class="math inline">\(d_{rm}\)</span>, is that they require the correlation between conditions. In practice, correlations between conditions are frequently not reported. An alternative estimator of Cohen’s <span class="math inline">\(d\)</span> in repeated measures design is to simply use the classic variation of cohen’s <span class="math inline">\(d\)</span> (i.e., pooled standard deviation). In a repeated measures design, the sample size does not change between conditions. Therefore weighting the variance of condition 1 and condition 2 by their respective degrees of freedom (i.e., <span class="math inline">\(df=n-1\)</span>) is an unnecessary step. Instead, we can standardize by the square root of the average the variances of condition 1 and 2 <span class="citation" data-cites="algina2003">(see equation 5, <a href="references.html#ref-algina2003" role="doc-biblioref">Algina and Keselman 2003</a>)</span>:</p>
<p><span class="math display">\[
d_{av} = \frac{M_2 - M_1}{\sqrt{\frac{S_1^2 + S_2^2}{2}}}
\]</span></p>
<p>This formulation is convenient especially when the correlation is not present, however without the correlation it fails to take into account the consistency of change between conditions. The standard error of the <span class="math inline">\(d_{av}\)</span> can be expressed as <span class="citation" data-cites="algina2003">(equation 9, <a href="references.html#ref-algina2003" role="doc-biblioref">Algina and Keselman 2003</a>)</span>,</p>
<p><span class="math display">\[
SE_{d_{av}}= \sqrt{\frac{2(S^2_1 + S^2_2 - 2rS_1S_2)}{n(S_1^2+S^2)}}
\]</span></p>
<p>In R, we can use the <code>d.ind.t.rm</code> function from the <code>MOTE</code> package to calculate the repeated measures standardized mean difference (<span class="math inline">\(d_{rm}\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for repeated measures (average variance)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given means and SDs </span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 1 Mean = 30.4, SD = 22.53, N = 96</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Condition 2 Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>stats <span class="ot">&lt;-</span> <span class="fu">d.dep.t.avg</span>(</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">m1 =</span> <span class="fl">30.4</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">m2 =</span> <span class="fl">21.4</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd1 =</span> <span class="fl">22.53</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd2 =</span> <span class="fl">19.59</span>,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="dv">96</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">a =</span> <span class="fl">0.05</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>d), </span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dlow), </span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(stats<span class="sc">$</span>dhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.427 0.217 0.635</code></pre>
</div>
</div>
<p>The output shows that the effect size is <span class="math inline">\(d_{av}\)</span> = 0.43, 95% CI [0.22, 0.64].</p>
</section>
<section id="sec-becker" class="level3" data-number="8.4.4">
<h3 data-number="8.4.4" class="anchored" data-anchor-id="sec-becker"><span class="header-section-number">8.4.4</span> Becker’s <span class="math inline">\(d\)</span> (<span class="math inline">\(d_b\)</span>)</h3>
<p>An even simpler variant of repeated measures <span class="math inline">\(d\)</span> value comes from <span class="citation" data-cites="becker1988">Becker (<a href="references.html#ref-becker1988" role="doc-biblioref">1988</a>)</span>. Becker’s <span class="math inline">\(d\)</span> standardizes simply by the pre-test standard deviation when the comparison is a pre/post design,</p>
<p><span class="math display">\[
d_b = \frac{M_{\text{post}}-M_{\text{pre}}}{S_{\text{pre}}}.
\]</span></p>
<p>The convenient interpretation of “change in baseline standard deviations” can be quite useful. We can also obtain the standard error with <span class="citation" data-cites="becker1988">(equation 13, <a href="references.html#ref-becker1988" role="doc-biblioref">Becker 1988</a>)</span>,</p>
<p><span class="math display">\[
SE_{d_b} = \sqrt{\frac{2(1-r)}{n}+\frac{d_b^2}{2n}}
\]</span></p>
<p>Notice that even though the formula for calculating <span class="math inline">\(d_b\)</span> did not include the correlation coefficient, the standard error does.</p>
<p>In base R, we can calculate Becker’s formulation of standardized mean difference using the equations above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the package below if not done so already</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(escalc)</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d for repeated measures (becker's d)</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># given means, the pre-test SDs, and the correlation</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-test Mean = 21.4, SD = 19.59, N = 96</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-test Mean = 30.4, N = 96</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation between conditions: r = .40</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>Mpre <span class="ot">&lt;-</span> <span class="fl">21.4</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>Mpost <span class="ot">&lt;-</span> <span class="fl">30.4</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>Spre <span class="ot">&lt;-</span> <span class="fl">19.59</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> .<span class="dv">40</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">96</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> (Mpost <span class="sc">-</span> Mpre) <span class="sc">/</span> Spre</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>r)<span class="sc">/</span>n <span class="sc">+</span> d<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>n) )</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(d), </span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(d <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>SE), </span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(d <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>SE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.459 0.231 0.688</code></pre>
</div>
</div>
<p>The output shows that the effect size is <span class="math inline">\(d_{rm}\)</span> = 0.46, 95% CI [0.23, 0.69].</p>
</section>
<section id="comparing-repeated-measures-d-values" class="level3" data-number="8.4.5">
<h3 data-number="8.4.5" class="anchored" data-anchor-id="comparing-repeated-measures-d-values"><span class="header-section-number">8.4.5</span> Comparing Repeated Measures <span class="math inline">\(d\)</span> values</h3>
<p><a href="#fig-correlation-comp">Figure&nbsp;<span>8.2</span></a> shows repeated measures designs with a high (<span class="math inline">\(r=\)</span> .95) and low (<span class="math inline">\(r=\)</span> .05) correlation between conditions. Let us fix the standard deviations and means for both conditions (i.e., high and low correlation) and only vary the correlation. Now we can compare the repeated measures estimators based on these two conditions shown in <a href="#fig-correlation-comp">Figure&nbsp;<span>8.2</span></a>:</p>
<ul>
<li>High correlation:
<ul>
<li><span class="math inline">\(d_z=1.24\)</span></li>
<li><span class="math inline">\(d_{rm}=0.39\)</span></li>
<li><span class="math inline">\(d_{av}=0.43\)</span></li>
<li><span class="math inline">\(d_{b}=0.40\)</span></li>
</ul></li>
<li>Low correlation:
<ul>
<li><span class="math inline">\(d_z=0.31\)</span></li>
<li><span class="math inline">\(d_{rm}=0.43\)</span></li>
<li><span class="math inline">\(d_{av}=0.43\)</span></li>
<li><span class="math inline">\(d_{b}=0.40\)</span></li>
</ul></li>
</ul>
<p>We notice that the correlation greatly influences <span class="math inline">\(d_z\)</span> more than any other estimator. The <span class="math inline">\(d_{rm}\)</span> value has very little change, whereas <span class="math inline">\(d_{av}\)</span> and <span class="math inline">\(d_{b}\)</span> do not take into account the correlation at all.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-correlation-comp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Standardized-Mean-Differences_files/figure-html/fig-correlation-comp-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figure&nbsp;8.2: Figure displaying simulated data of a repeated measures design, the x-axis shows the condition (e.g., pre-test and post-test) and y-axis is the scores. Left panel shows a high pre/post correlation (<span class="math inline">\(r\)</span> = .95) and right panel shows a low correlation condition (<span class="math inline">\(r\)</span> = .05). Lines indicate within person pre/post change.</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-ppc" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="sec-ppc"><span class="header-section-number">8.5</span> Pretest-Posttest-Control Group Designs</h2>
<p>In many areas of research both between and within group factors are incorporated. For example, in research involving the examination of the effects of an intervention often a sample is randomised into two seperate groups (intervention and control) and then they are measured on the outcome of interest both before (pretest) and after (posttest) the intervention/control period. In these types of 2x2 (group x time) study designs it is usually the difference between the standardised mean change for the intervention/treatment (<span class="math inline">\(T\)</span>) and control (<span class="math inline">\(C\)</span>) groups that is of interest. For a visualization of a pretest-posttest-control group design see <a href="#fig-ppc">Figure&nbsp;<span>8.3</span></a>.</p>
<p><span class="citation" data-cites="morris2008">Morris (<a href="references.html#ref-morris2008" role="doc-biblioref">2008</a>)</span> details three effect sizes for this pretest-posttest-control (PPC).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ppc" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Standardized-Mean-Differences_files/figure-html/fig-ppc-1.png" class="img-fluid figure-img" width="2100"></p>
<figcaption class="figure-caption">Figure&nbsp;8.3: Illustration of a pre-post control design. Left panel shows the pre-post difference in the control group and right panel shows the pre-post difference in the intervention/treatment group. Lines indicate within person pre/post change.</figcaption>
</figure>
</div>
</div>
</div>
<section id="sec-ppc1" class="level3" data-number="8.5.1">
<h3 data-number="8.5.1" class="anchored" data-anchor-id="sec-ppc1"><span class="header-section-number">8.5.1</span> PPC1 - separate pre-test standard deviations</h3>
<p>The separate pre-test (i.e., baseline) standard deviations are used to standardize the pre/post mean difference in the intervention group and the control group respectively <span class="citation" data-cites="morris2008">(see equation 4, <a href="references.html#ref-morris2008" role="doc-biblioref">Morris 2008</a>)</span>,</p>
<p><span class="math display">\[
d_T = \frac{M_{T,\text{post}} - M_{T,\text{pre}}}{S_{T,\text{pre}}}
\]</span></p>
<p><span class="math display">\[
d_C = \frac{M_{C,\text{post}} - M_{C,\text{pre}}}{S_{C,\text{pre}}}
\]</span></p>
<p>Note that these effect sizes are identical to the Becker’s <span class="math inline">\(d\)</span> formulation of the SMD (see <a href="#sec-becker"><span>Section&nbsp;8.4.4</span></a>). Therefore the pretest-posttest-control group effect size is simply the difference between the intervention and control pre/post SMD <span class="citation" data-cites="becker1988">(equation 15, <a href="references.html#ref-becker1988" role="doc-biblioref">Becker 1988</a>)</span>,</p>
<p><span class="math display">\[
d_{PPC1} = d_T - d_C
\]</span></p>
<p>The asymptotic standard error of <span class="math inline">\(d_{PPC2}\)</span> was first derived by <span class="citation" data-cites="becker1988">Becker (<a href="references.html#ref-becker1988" role="doc-biblioref">1988</a>)</span> and can be expressed as the square root of the sum of the sampling variances <span class="citation" data-cites="becker1988">(equation 16, <a href="references.html#ref-becker1988" role="doc-biblioref">Becker 1988</a>)</span></p>
<p><span class="math display">\[
SE_{d_{PPC1}} = \sqrt{\left[\frac{2(1-r_T)}{n_T} + \frac{d_T}{2n_T}\right] + \left[\frac{2(1-r_C)}{n_C} + \frac{d_C}{2n_C}\right]}
\]</span></p>
<p>We can calculate <span class="math inline">\(d_{PPC1}\)</span> and it’s confidence intervals using base R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example:</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Control Group (N = 90)</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 6</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 25, SD = 7</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>M_Cpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>M_Cpost <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>SD_Cpre <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>SD_Cpost <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>rC <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>nC <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervention Group (N = 90)</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 5</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 27, SD = 8</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>M_Tpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>M_Tpost <span class="ot">&lt;-</span> <span class="dv">27</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>SD_Tpre <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>SD_Tpost <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>rT <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>nT <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the observed standardized mean difference</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>dT <span class="ot">&lt;-</span> (M_Tpost<span class="sc">-</span> M_Tpre) <span class="sc">/</span> SD_Tpre</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>dC <span class="ot">&lt;-</span> (M_Cpost <span class="sc">-</span> M_Cpre) <span class="sc">/</span> SD_Cpre</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>dPPC1 <span class="ot">&lt;-</span> dT <span class="sc">-</span> dC</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the standard error</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>( <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rT)<span class="sc">/</span>nT <span class="sc">+</span> dPPC1<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>nT) <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rC)<span class="sc">/</span>nC <span class="sc">+</span> dPPC1<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>nC) )</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="co"># print the d value and confidence intervals</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC1),</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC1 <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>SE),</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC1 <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>SE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.567 0.252 0.881</code></pre>
</div>
</div>
<p>The output shows a pre-post intervention effect of <span class="math inline">\(d_{PPC1}\)</span> = 0.57 [0.25, 0.88].</p>
</section>
<section id="sec-ppc2" class="level3" data-number="8.5.2">
<h3 data-number="8.5.2" class="anchored" data-anchor-id="sec-ppc2"><span class="header-section-number">8.5.2</span> PPC2 - pooled pre-test standard deviations</h3>
<p>The pooled pre-test (i.e., baseline) standard deviations can be used to standardized the difference in pre/post change between intervention and control groups such that <span class="citation" data-cites="morris2008">(equation 8, <a href="references.html#ref-morris2008" role="doc-biblioref">Morris 2008</a>)</span>,</p>
<p><span class="math display">\[
d_{PPC2} = \frac{(M_{T,\text{post}} - M_{T,\text{pre}}) - (M_{C,\text{post}} - M_{C,\text{pre}})}{S_{p,\text{pre}}}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
S_{p,\text{pre}} = \sqrt{\frac{(n_T-1)S^2_{T,\text{pre}} + (n_C - 1)S^2_{C,\text{post}}}{n_T + n_C - 2}}.
\]</span></p>
<p>The distribution of <span class="math inline">\(d_{PPC2}\)</span> was described by <span class="citation" data-cites="morris2008">Morris (<a href="references.html#ref-morris2008" role="doc-biblioref">2008</a>)</span> and can be expressed as <span class="citation" data-cites="morris2008">(adapted from equation 16, <a href="references.html#ref-morris2008" role="doc-biblioref">Morris 2008</a>)</span>,</p>
<p><span class="math display">\[
\small{SE_{d_{PPC2}} = \sqrt{2\left(1-\frac{n_T r_T + n_C r_C}{n_T + n_C}\right)\left(\frac{n_T + n_C}{n_T n_C}\right)\left[1 + \frac{d^2_{PPC2}}{2\left(1-\frac{n_T r_T + n_C r_C}{n_T + n_C}\right)\left(\frac{n_T + n_C}{n_T n_C}\right)}\right] - d^2_{PPC2}}}
\]</span></p>
<p>Note the original equation shown in the paper by <span class="citation" data-cites="morris2008">Morris (<a href="references.html#ref-morris2008" role="doc-biblioref">2008</a>)</span> uses the population pre/post correlation <span class="math inline">\(\rho\)</span>, however in the equation above we replace <span class="math inline">\(\rho\)</span> with the sample size weighted average of the Pearson correlation computed in the treatment group and the control group (i.e., <span class="math inline">\(\rho \approx \frac{n_T r_T + n_C r_C}{n_T + n_C}\)</span>).</p>
<p>We can use base R to obtain <span class="math inline">\(d_{PPC2}\)</span> and confidence intervals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example:</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Control Group (N = 90)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 6</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 25, SD = 7</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>M_Cpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>M_Cpost <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>SD_Cpre <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>SD_Cpost <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>rC <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>nC <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervention Group (N = 90)</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 5</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 27, SD = 8</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>M_Tpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>M_Tpost <span class="ot">&lt;-</span> <span class="dv">27</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>SD_Tpre <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>SD_Tpost <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>rT <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>nT <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the observed standardized mean difference</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>dPPC2 <span class="ot">&lt;-</span> ((M_Tpost<span class="sc">-</span> M_Tpre) <span class="sc">-</span> (M_Cpost <span class="sc">-</span> M_Cpre)) <span class="sc">/</span> <span class="fu">sqrt</span>( ( (nT <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(SD_Tpre<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (nC <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(SD_Cpre<span class="sc">^</span><span class="dv">2</span>) ) <span class="sc">/</span> (nT <span class="sc">+</span> nC <span class="sc">-</span> <span class="dv">2</span>) )</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the standard error</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span>  <span class="fu">sqrt</span>(<span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>( (nT<span class="sc">*</span>rT<span class="sc">+</span>nC<span class="sc">*</span>rC)<span class="sc">/</span>(nT <span class="sc">+</span> nC))) <span class="sc">*</span> ((nT<span class="sc">+</span>nC)<span class="sc">/</span>(nT<span class="sc">*</span>nC)) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> (dPPC2<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> ((nT<span class="sc">*</span>rT<span class="sc">+</span>nC<span class="sc">*</span>rC)<span class="sc">/</span>(nT<span class="sc">+</span>nC))) <span class="sc">*</span> ((nT<span class="sc">+</span>nC)<span class="sc">/</span>(nT<span class="sc">*</span>nC)))))) <span class="sc">-</span> dPPC2</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="co"># print the d value and confidence intervals</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC2),</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC2 <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>SE),</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC2 <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>SE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.362 0.304 0.420</code></pre>
</div>
</div>
<p>The output shows a pre-post intervention effect of <span class="math inline">\(d_{PPC2}\)</span> = 0.36 [0.30, 0.42].</p>
</section>
<section id="sec-ppc3" class="level3" data-number="8.5.3">
<h3 data-number="8.5.3" class="anchored" data-anchor-id="sec-ppc3"><span class="header-section-number">8.5.3</span> PPC3 - pooled pre- and post-test</h3>
<p>The two previous effect sizes only use the pretest standard deviation. But if we are happy to assume that pretest and posttest variances are homogenous<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> the pooled pre-test and post-test standard deviations can be used to standardized the difference in pre/post change between intervention and control groups such that <span class="citation" data-cites="morris2008">(equation 8, <a href="references.html#ref-morris2008" role="doc-biblioref">Morris 2008</a>)</span>,</p>
<p><span class="math display">\[
d_{PPC3} = \frac{(M_{T,\text{post}} - M_{T,\text{pre}}) - (M_{C,\text{post}} - M_{C,\text{pre}})}{S_{p,\text{pre-post}}},
\]</span></p>
<p>where,</p>
<p><span class="math display">\[
S_{p,\text{pre-post}} = \sqrt{\frac{(n_T-1)\left(S^2_{T,\text{pre}} + S^2_{T,\text{post}}\right) + (n_C - 1)\left(S^2_{C,\text{pre}} + S^2_{C,\text{post}}\right)}{n_T + n_C - 2}}.
\]</span></p>
<p>The standard error for <span class="math inline">\(d_{PPC2}\)</span> is currently unknown. An option to estimate this standard error is to use a non-parametric or parametric bootstrap by repeatedly sampling the raw data, or if the raw data is not available resample simulated data. We can do this in base R by simulating pre/post data using the <code>mvrnorm()</code> function from the <code>MASS</code> package <span class="citation" data-cites="MASS">(<a href="references.html#ref-MASS" role="doc-biblioref">Venables and Ripley 2002</a>)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the package below if not done so already</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(MASS)</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Example:</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Control Group (N = 90)</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 6</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 25, SD = 7</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>M_Cpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>M_Cpost <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>SD_Cpre <span class="ot">&lt;-</span> <span class="dv">6</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>SD_Cpost <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>rC <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>nC <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervention Group (N = 90)</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre-test Mean = 20, SD = 5</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="do">## Post-test Mean = 27, SD = 8</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="do">## Pre/post correlation = .50</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>M_Tpre <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>M_Tpost <span class="ot">&lt;-</span> <span class="dv">27</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>SD_Tpre <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>SD_Tpost <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>rT <span class="ot">&lt;-</span> .<span class="dv">50</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>nT <span class="ot">&lt;-</span> <span class="dv">90</span></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="co"># simulate data</span></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>) <span class="co"># set seed for reproducibility</span></span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>boot_dPPC3 <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>  <span class="co"># simulate control group pre-post data</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>  data_C <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> nC,</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># input observed means</span></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a>                          <span class="at">mu =</span> <span class="fu">c</span>(M_Cpre,M_Cpost),</span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># input observed covariance matrix</span></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Sigma =</span> <span class="fu">data.frame</span>(<span class="at">pre =</span> <span class="fu">c</span>(SD_Cpre<span class="sc">^</span><span class="dv">2</span>, rC<span class="sc">*</span>SD_Cpre<span class="sc">*</span>SD_Cpost), </span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">post =</span> <span class="fu">c</span>(rC<span class="sc">*</span>SD_Cpre<span class="sc">*</span>SD_Cpost,SD_Cpost<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>  <span class="co"># simulate intervention group pre-post data</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>  data_T <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">mvrnorm</span>(<span class="at">n =</span> nT,</span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># input observed means</span></span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a>                          <span class="at">mu =</span> <span class="fu">c</span>(M_Tpre,M_Tpost),</span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a>                          <span class="co"># input observed covariance matrix</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a>                          <span class="at">Sigma =</span> <span class="fu">data.frame</span>(<span class="at">pre =</span> <span class="fu">c</span>(SD_Tpre<span class="sc">^</span><span class="dv">2</span>, rT<span class="sc">*</span>SD_Tpre<span class="sc">*</span>SD_Tpost), </span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">post =</span> <span class="fu">c</span>(rT<span class="sc">*</span>SD_Tpre<span class="sc">*</span>SD_Tpost,SD_Tpost<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the mean difference in pre/post change (the numerator)</span></span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a>  MeanDiff <span class="ot">&lt;-</span> (<span class="fu">mean</span>(data_T[,<span class="dv">2</span>]) <span class="sc">-</span> <span class="fu">mean</span>(data_T[,<span class="dv">1</span>])) <span class="sc">-</span> (<span class="fu">mean</span>(data_C[,<span class="dv">2</span>]) <span class="sc">-</span> <span class="fu">mean</span>(data_C[,<span class="dv">1</span>]))</span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the pooled pre-post standard deviation (the denominator)</span></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a>  S_Pprepost <span class="ot">&lt;-</span>  <span class="fu">sqrt</span>( ( (nT <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">sd</span>(data_T[,<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span><span class="fu">sd</span>(data_T[,<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (nC <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">sd</span>(data_C[,<span class="dv">1</span>])<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span><span class="fu">sd</span>(data_C[,<span class="dv">2</span>])<span class="sc">^</span><span class="dv">2</span>) ) <span class="sc">/</span> (nT <span class="sc">+</span> nC <span class="sc">-</span> <span class="dv">2</span>) )</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a>  <span class="co"># calculate the standardized mean difference for each bootstrap iteration</span></span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a>  boot_dPPC3[i] <span class="ot">&lt;-</span> MeanDiff <span class="sc">/</span> S_Pprepost</span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate bootstrapped standard error</span></span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">&lt;-</span> <span class="fu">sd</span>(boot_dPPC3)</span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the observed standardized mean difference</span></span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a>dPPC3 <span class="ot">&lt;-</span> ((M_Tpost<span class="sc">-</span> M_Tpre) <span class="sc">-</span> (M_Cpost <span class="sc">-</span> M_Cpre)) <span class="sc">/</span> <span class="fu">sqrt</span>( ( (nT <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(SD_Tpre<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>SD_Tpost<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> (nC <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(SD_Cpre<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span>SD_Cpost<span class="sc">^</span><span class="dv">2</span>) ) <span class="sc">/</span> (nT <span class="sc">+</span> nC <span class="sc">-</span> <span class="dv">2</span>) )</span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a><span class="co">#print the d value and confidence intervals</span></span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC3),</span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC3 <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>SE),</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(dPPC3 <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>SE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.214 0.002 0.427</code></pre>
</div>
</div>
<p>The output shows a pre-post intervention effect of <span class="math inline">\(d_{PPC3}\)</span> = 0.21 [0.002, 0.43].</p>
</section>
</section>
<section id="small-sample-bias-in-d-values" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="small-sample-bias-in-d-values"><span class="header-section-number">8.6</span> Small Sample Bias in <span class="math inline">\(d\)</span> values</h2>
<p>All the estimators of <span class="math inline">\(d\)</span> listed above are biased estimates of the population <span class="math inline">\(d\)</span> value, specifically they all over-estimate the population value in small sample sizes. To adjust for this bias, we can apply a correction factor based on the degrees of freedom. The degrees of freedom will largely depend on the estimator used. The degrees of freedom for each estimator is listed below:</p>
<ul>
<li>Single Group design (<span class="math inline">\(d_s\)</span>): <span class="math inline">\(df = n-1\)</span></li>
<li>Between Groups - Pooled Standard Deviation (<span class="math inline">\(d_p\)</span>): <span class="math inline">\(df = n_1+n_2-2\)</span></li>
<li>Between Groups - Control Group Standard Deviation (<span class="math inline">\(d_\Delta\)</span>): <span class="math inline">\(df = n_C-1\)</span></li>
<li>Repeated Measures - all types (<span class="math inline">\(d_z\)</span>, <span class="math inline">\(d_{rm}\)</span>, <span class="math inline">\(d_{av}\)</span>, <span class="math inline">\(d_{b}\)</span>): <span class="math inline">\(df = n-1\)</span></li>
<li>Pretest-Posttest-Control Separate Standard Deviation (<span class="math inline">\(d_{PPC1}\)</span>): <span class="math inline">\(df=n_C−1\)</span></li>
<li>Pretest-Posttest-Control Pooled Pretest Standard Deviation (<span class="math inline">\(d_{PPC2}\)</span>): <span class="math inline">\(df=n_T+n_C−2\)</span></li>
<li>Pretest-Posttest-Control Pooled Pretest and Posttest Standard Deviation (<span class="math inline">\(d_{PPC3}\)</span>): <span class="math inline">\(df=2(n_T+n_C−2)\)</span></li>
</ul>
<p>With the appropriate degrees of freedom, we can use the following correction factor, <span class="math inline">\(CF\)</span>, to obtain an unbiased estimate of the population standardized mean difference:</p>
<p><span class="math display">\[
CF = \frac{\Gamma\left(\frac{df}{2}\right)}{\Gamma\left(\frac{df-1}{2}\right)\sqrt{\frac{df}{2}}}
\]</span></p>
<p>Where <span class="math inline">\(\Gamma(\cdot)\)</span> is the gamma function. An approximation of this complex formula given by <span class="citation" data-cites="hedges1981">Hedges (<a href="references.html#ref-hedges1981" role="doc-biblioref">1981</a>)</span> can be written as <span class="math inline">\(CF\approx 1-\frac{3}{4\cdot df -1}\)</span>. In R, this can be calculated using,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 1 sample size = 20</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 2 sample size = 18</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> n1 <span class="sc">+</span> n2 <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>CF <span class="ot">&lt;-</span> <span class="fu">gamma</span>(df<span class="sc">/</span><span class="dv">2</span>) <span class="sc">/</span> ( <span class="fu">sqrt</span>(df<span class="sc">/</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">gamma</span>((df<span class="dv">-1</span>)<span class="sc">/</span><span class="dv">2</span>) )</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>CF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9789964</code></pre>
</div>
</div>
<p>This correction factor can then be applied to any of the estimators mentioned above,</p>
<p><span class="math display">\[
d^* = d\times CF
\]</span></p>
<p>The corrected <span class="math inline">\(d\)</span> value, <span class="math inline">\(d^*\)</span>, is commonly referred to as Hedges’ <span class="math inline">\(g\)</span> or just <span class="math inline">\(g\)</span>. To avoid notation confusion we will just add an asterisk to <span class="math inline">\(d\)</span> to denote the correction. We also need to correct the standard error for <span class="math inline">\(d^*\)</span></p>
<p><span class="math display">\[
SE_{d^*} = SE_{d} \times CF
\]</span></p>
<p>These standard errors can then be used to calculate the confidence interval of the corrected <span class="math inline">\(d\)</span> value,</p>
<p><span class="math display">\[
CI_{d*} = d^* \pm 1.96\times SE_{d^*}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example:</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cohen's d = .50, SE = .10</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> .<span class="dv">50</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>SE <span class="ot">=</span> .<span class="dv">10</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># correct d value and CIs small sample bias</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>d_corrected <span class="ot">&lt;-</span> d <span class="sc">*</span> CF</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>SE_corrected <span class="ot">&lt;-</span> SE <span class="sc">*</span> CF</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>dlow_corrected <span class="ot">&lt;-</span> d_corrected <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>SE_corrected</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>dhigh_corrected <span class="ot">&lt;-</span> d_corrected <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>SE_corrected</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># print just the d value and confidence intervals</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">d =</span> <span class="fu">apa</span>(d), </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">dlow =</span> <span class="fu">apa</span>(dlow_corrected), </span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">dhigh =</span> <span class="fu">apa</span>(dhigh_corrected))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      d  dlow dhigh
1 0.500 0.298 0.681</code></pre>
</div>
</div>
<p>The output shows that the corrected effect size is <span class="math inline">\(d^*\)</span> = 0.50, 95% CI [0.30, 0.68].</p>
</section>
<section id="sec-rr" class="level2" data-number="8.7">
<h2 data-number="8.7" class="anchored" data-anchor-id="sec-rr"><span class="header-section-number">8.7</span> Ratios of Means</h2>
<p>Another common approach, particularly within the fields of ecology and evolution, is to take the natural logarithm of the ratio between two means; the so-called Response Ratio (<span class="math inline">\(lnRR\)</span>). This is sometimes more favorable as, due to its construction using the standard deviation in some form as a denominator, the various versions of standardized mean differences are impacted by the estimate of this parameter for which studies are often less powered compared to mean magnitudes <span class="citation" data-cites="yang2022">(<a href="references.html#ref-yang2022" role="doc-biblioref">Yang et al. 2022</a>)</span>. For the <span class="math inline">\(lnRR\)</span> however the standard deviation only impacts its variance estimation and not the point estimate. A limitation of the lnRR however is that it is limited to data that are observed on a ratio scale (i.e., have an absolute zero and instances of it are related ordinally and additively meaning both means will be positive).</p>
<p>Although strictly speaking the <span class="math inline">\(lnRR\)</span> is not a difference in means in an additive sense as the above standardized mean difference effect sizes are, it can in one sense be considered to reflect the difference in means on the multiplicative scale. In fact, after calculation it is often transformed to reflect the percentage difference or change between means: <span class="math inline">\(100\times \exp(lnRR)-1\)</span>. However, this can introduce transformation induced bias because a non-linear transformation of a mean value is not generally equal to the mean of the transformed value. In the context of meta-analysis combining <span class="math inline">\(lnRR\)</span> estimated across studies a correct factor can be applied: <span class="math inline">\(100\times \exp(lnRR+0.5 S^2_\text{total})-1\)</span>, where <span class="math inline">\(S^2_\text{total}\)</span> is the variance of all <span class="math inline">\(lnRR\)</span> values.</p>
<p>Similarly to the various standardized mean differences, there are varied calculations for the lnRR dependent upon the study design being used <span class="citation" data-cites="senior2020">(see <a href="references.html#ref-senior2020" role="doc-biblioref">Senior, Viechtbauer, and Nakagawa 2020</a>)</span>.</p>
<section id="sec-rrind" class="level3" data-number="8.7.1">
<h3 data-number="8.7.1" class="anchored" data-anchor-id="sec-rrind"><span class="header-section-number">8.7.1</span> lnRR for Independent Groups (<span class="math inline">\(lnRR_\text{ind}\)</span>)</h3>
<p>The lnRR can be calculated when groups are independent as follows,</p>
<p><span class="math display">\[
lnRR_\text{ind}=\ln\left(\frac{M_T}{M_C}\right)+CF
\]</span></p>
<p>Where <span class="math inline">\(M_T\)</span> and <span class="math inline">\(M_C\)</span> are the means for the treatment and control group respectively and <span class="math inline">\(CF\)</span> is the small sample correction factor calculated as,</p>
<p><span class="math display">\[
CF = \frac{S^2_T}{2n_TM_T^2} - \frac{S^2_C}{2n_CM_C^2}
\]</span></p>
<p>The standard error can be calculated as,</p>
<p><span class="math display">\[
SE_{lnRR_\text{ind}} = \sqrt{ \frac{S^2_T}{n_T M_T^2} + \frac{S^2_C}{n_C M_C^2} +\frac{S^4_T}{2n^2_T M_T^4} + \frac{S^4_C}{2n^2_C M_C^4}}
\]</span></p>
<p>Using R we can easily calculate this effect size using the <code>escalc()</code> function in the <code>metafor</code> package <span class="citation" data-cites="metafor">(<a href="references.html#ref-metafor" role="doc-biblioref">Viechtbauer 2010</a>)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lnRR for two independent groups</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given means and SDs</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 1 Mean = 30.4, Standard deviation = 22.53, Sample size = 96</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 2 Mean = 21.4, Standard deviation = 19.59, Sample size = 96</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare the data</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fl">30.4</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fl">21.4</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>SD1 <span class="ot">&lt;-</span> <span class="fl">22.53</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>SD2 <span class="ot">&lt;-</span> <span class="fl">19.59</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>N1 <span class="ot">=</span> <span class="dv">96</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>N2 <span class="ot">=</span> <span class="dv">96</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate lnRRind and standard error</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>lnRRind <span class="ot">&lt;-</span> <span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">"ROM"</span>, </span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>               <span class="at">m1i =</span> M1,</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>               <span class="at">m2i =</span> M2,</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>               <span class="at">sd1i =</span> SD1,</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>               <span class="at">sd2i =</span> SD2,</span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>               <span class="at">n1i =</span> N1,</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>               <span class="at">n2i =</span> N2)</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>lnRRind<span class="sc">$</span>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(lnRRind<span class="sc">$</span>vi)</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate confidence interval</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>lnRRind<span class="sc">$</span>CIlow <span class="ot">&lt;-</span> lnRRind<span class="sc">$</span>yi <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>lnRRind<span class="sc">$</span>SE</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>lnRRind<span class="sc">$</span>CIhigh <span class="ot">&lt;-</span>  lnRRind<span class="sc">$</span>yi <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>lnRRind<span class="sc">$</span>SE</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co"># print the VR value and confidence intervals</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">lnRRind =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRind<span class="sc">$</span>yi),</span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>           <span class="at">lnRRind_low =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRind<span class="sc">$</span>CIlow),</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>           <span class="at">lnRRind_high =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRind<span class="sc">$</span>CIhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lnRRind lnRRind_low lnRRind_high
1   0.351       0.115        0.587</code></pre>
</div>
</div>
<p>The example shwos a natural log response ratio of <span class="math inline">\(lnRR_\text{ind}\)</span> = 0.35 [0.12, 0.59].</p>
</section>
<section id="sec-rrdep" class="level3" data-number="8.7.2">
<h3 data-number="8.7.2" class="anchored" data-anchor-id="sec-rrdep"><span class="header-section-number">8.7.2</span> lnRR for dependent groups (<span class="math inline">\(lnRR_\text{dep}\)</span>)</h3>
<p>The lnRR can be calculated when groups are dependent (i.e., same subjects in both conditions), for example a pre-post comparison, as follows,</p>
<p><span class="math display">\[
lnRR_\text{dep} = \ln\left(\frac{M_2}{M_1}\right) + CF
\]</span></p>
<p>Where <span class="math inline">\(CF\)</span> is the small sample correct factor calculated as,</p>
<p><span class="math display">\[
CF = \frac{S^2_2}{2nM^2_2} - \frac{S^2_1}{2nM^2_1}
\]</span></p>
<p>The standard error can then be calculated as,</p>
<p><span class="math display">\[
\small{SE_{lnRR_\text{dep}} = \sqrt{ \frac{S^2_1}{n M_1^2} + \frac{S^2_2}{n M_2^2} + \frac{S^4_1}{2n^2M^4_1} +  \frac{S^4_2}{2n^2M^4_2} + \frac{2rS_1 S_2}{n M_1 M_2} + \frac{r^2S^2_1 S^2_2 (M_1^4 + M_2^4)}{2n^2 M_1^4 M_2^4}}}
\]</span></p>
<p>Using R we can easily calculate this effect size using the <code>escalc()</code> function from the <code>metafor</code> package as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lnRR for two dependent groups</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># given means and SDs</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># For example:</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean 1 = 30.4, Standard deviation 1 = 22.53</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean 2 = 21.4, Standard deviation 2 = 19.59</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample size = 96</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation = 0.4</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co"># prepare the data</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fl">30.4</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fl">21.4</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>SD1 <span class="ot">&lt;-</span> <span class="fl">22.53</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>SD2 <span class="ot">&lt;-</span> <span class="fl">19.59</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>N <span class="ot">=</span> <span class="dv">96</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>R <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate lnRR and standard error</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>lnRRdep <span class="ot">&lt;-</span> <span class="fu">escalc</span>(<span class="at">measure =</span> <span class="st">"ROMC"</span>, </span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>               <span class="at">m1i =</span> M1,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>               <span class="at">m2i =</span> M2,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>               <span class="at">sd1i =</span> SD1,</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>               <span class="at">sd2i =</span> SD2,</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>               <span class="at">ni =</span> N,</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>               <span class="at">ri =</span> R)</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain standard error from sqrt of sampling variance</span></span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>lnRRdep<span class="sc">$</span>SE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(lnRRdep<span class="sc">$</span>vi)</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate confidence interval</span></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>lnRRdep<span class="sc">$</span>CIlow <span class="ot">&lt;-</span> lnRRdep<span class="sc">$</span>yi <span class="sc">-</span> <span class="fl">1.96</span><span class="sc">*</span>lnRRdep<span class="sc">$</span>SE</span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>lnRRdep<span class="sc">$</span>CIhigh <span class="ot">&lt;-</span>  lnRRdep<span class="sc">$</span>yi <span class="sc">+</span> <span class="fl">1.96</span><span class="sc">*</span>lnRRdep<span class="sc">$</span>SE</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a><span class="co"># print the VR value and confidence intervals</span></span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">lnRRdep =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRdep<span class="sc">$</span>yi),</span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a>           <span class="at">lnRRdep_low =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRdep<span class="sc">$</span>CIlow),</span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a>           <span class="at">lnRRdep_high =</span> MOTE<span class="sc">::</span><span class="fu">apa</span>(lnRRdep<span class="sc">$</span>CIhigh))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lnRRdep lnRRdep_low lnRRdep_high
1   0.351       0.167        0.535</code></pre>
</div>
</div>
<p>The example shwos a natural log response ratio of <span class="math inline">\(lnRR_\text{dep}\)</span> = 0.35 [0.17, 0.54].</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-algina2003" class="csl-entry" role="listitem">
Algina, James, and H. J. Keselman. 2003. <span>“Approximate Confidence Intervals for Effect Sizes.”</span> <em>Educational and Psychological Measurement</em> 63 (4): 537–53. <a href="https://doi.org/10.1177/0013164403256358">https://doi.org/10.1177/0013164403256358</a>.
</div>
<div id="ref-baayen2008mixed" class="csl-entry" role="listitem">
Baayen, R Harald, Douglas J Davidson, and Douglas M Bates. 2008. <span>“Mixed-Effects Modeling with Crossed Random Effects for Subjects and Items.”</span> <em>Journal of Memory and Language</em> 59 (4): 390–412.
</div>
<div id="ref-barr2013random" class="csl-entry" role="listitem">
Barr, Dale J, Roger Levy, Christoph Scheepers, and Harry J Tily. 2013. <span>“Random Effects Structure for Confirmatory Hypothesis Testing: Keep It Maximal.”</span> <em>Journal of Memory and Language</em> 68 (3): 255–78.
</div>
<div id="ref-becker1988" class="csl-entry" role="listitem">
Becker, Betsy J. 1988. <span>“Synthesizing Standardized Mean-Change Measures - UConn Library.”</span> <em>British Journal of Mathematical and Statistical Psychology</em> 41 (2): 257278. https://doi.org/<a href="https://doi.org/10.1111/j.2044-8317.1988.tb00901.x">https://doi.org/10.1111/j.2044-8317.1988.tb00901.x</a>.
</div>
<div id="ref-caldwell" class="csl-entry" role="listitem">
Caldwell, Aaron R. 2022. <span>“Exploring Equivalence Testing with the Updated TOSTER r Package.”</span> <em>PsyArXiv</em>. <a href="https://doi.org/10.31234/osf.io/ty8de">https://doi.org/10.31234/osf.io/ty8de</a>.
</div>
<div id="ref-cohen1988" class="csl-entry" role="listitem">
Cohen, Jacob. 1988. <em>Statistical Power Analysis for the Behavioral Sciences</em>. Academic Press.
</div>
<div id="ref-glass1981" class="csl-entry" role="listitem">
Glass, Gene V. 1981. <span>“Meta-Analysis in Social Research.”</span> <em>(No Title)</em>. <a href="https://cir.nii.ac.jp/crid/1130000795088566912">https://cir.nii.ac.jp/crid/1130000795088566912</a>.
</div>
<div id="ref-glass1981a" class="csl-entry" role="listitem">
Glass, Gene V., Barry McGaw, and Mary L. Smith. 1981. <span>“Meta-Analysis in Social Research.”</span> <em>(No Title)</em>. <a href="https://cir.nii.ac.jp/crid/1130000795088566912">https://cir.nii.ac.jp/crid/1130000795088566912</a>.
</div>
<div id="ref-hedges1981" class="csl-entry" role="listitem">
Hedges, Larry V. 1981. <span>“Distribution Theory for Glass’s Estimator of Effect Size and Related Estimators.”</span> <em>Journal of Educational Statistics</em> 6 (2): 107–28. <a href="https://doi.org/10.3102/10769986006002107">https://doi.org/10.3102/10769986006002107</a>.
</div>
<div id="ref-lakens2013" class="csl-entry" role="listitem">
Lakens, Daniël. 2013. <span>“Calculating and Reporting Effect Sizes to Facilitate Cumulative Science: A Practical Primer for t-Tests and ANOVAs.”</span> <em>Frontiers in Psychology</em> 4. <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863">https://www.frontiersin.org/articles/10.3389/fpsyg.2013.00863</a>.
</div>
<div id="ref-morris2008" class="csl-entry" role="listitem">
Morris, Scott B. 2008. <span>“Estimating Effect Sizes From Pretest-Posttest-Control Group Designs.”</span> <em>Organizational Research Methods</em> 11 (2): 364–86. <a href="https://doi.org/10.1177/1094428106291059">https://doi.org/10.1177/1094428106291059</a>.
</div>
<div id="ref-senior2020" class="csl-entry" role="listitem">
Senior, Alistair M., Wolfgang Viechtbauer, and Shinichi Nakagawa. 2020. <span>“Revisiting and Expanding the Meta-Analysis of Variation: The Log Coefficient of Variation Ratio.”</span> <em>Research Synthesis Methods</em> 11 (4): 553–67. <a href="https://doi.org/10.1002/jrsm.1423">https://doi.org/10.1002/jrsm.1423</a>.
</div>
<div id="ref-MASS" class="csl-entry" role="listitem">
Venables, W. N., and B. D. Ripley. 2002. <em>Modern Applied Statistics with s</em>. Fourth. New York: Springer. <a href="https://www.stats.ox.ac.uk/pub/MASS4/">https://www.stats.ox.ac.uk/pub/MASS4/</a>.
</div>
<div id="ref-metafor" class="csl-entry" role="listitem">
Viechtbauer, Wolfgang. 2010. <span>“Conducting Meta-Analyses in <span>R</span> with the <span class="nocase">metafor</span> Package.”</span> <em>Journal of Statistical Software</em> 36 (3): 1–48. <a href="https://doi.org/10.18637/jss.v036.i03">https://doi.org/10.18637/jss.v036.i03</a>.
</div>
<div id="ref-yang2022" class="csl-entry" role="listitem">
Yang, Yefeng, Helmut Hillebrand, Malgorzata Lagisz, Ian Cleasby, and Shinichi Nakagawa. 2022. <span>“Low Statistical Power and Overestimated Anthropogenic Impacts, Exacerbated by Publication Bias, Dominate Field Studies in Global Change Biology.”</span> <em>Global Change Biology</em> 28 (3): 969–89. <a href="https://doi.org/10.1111/gcb.15972">https://doi.org/10.1111/gcb.15972</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Note, this may not be the case especially where there is a mean-variance relationship and one (usually the intervention) group has a higher posttest mean score.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Artifacts-and-Bias.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Artifacts and Bias in Effect Sizes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Correlations.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>